# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uvE7RxqCG2ESOcxmFuf-Lpo-BA83kneh
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

df=pd.read_csv('/content/drive/MyDrive/Data/placement.csv')

df.head(2)

df.max()

df.min()

df.shape

x=np.array(df['cgpa'])
y=np.array(df['package'])
plt.xlabel("CGPA",size=20)
plt.ylabel("Package",size=20)

plt.scatter(x,y,color='green')

plt.show()

#independent and dependent feature
x=df.iloc[:,0:1]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
X_test.head()

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr=lr.fit(X_train,y_train)

lr.predict(X_test.iloc[0].values.reshape(1,1))

plt.scatter(df['cgpa'],df['package'])
plt.plot(X_train,lr.predict(X_train),color='r')
plt.show()

lr.predict(np.array([9.13]).reshape(1,1))

m=lr.coef_

b=lr.intercept_

m*9.13+b

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
y_pred=lr.predict(X_test)
y_test.values

print("MAE",mean_absolute_error(y_test,y_pred))

print("MSE",mean_squared_error(y_test,y_pred))

print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

print("R2 Score",r2_score(y_test,y_pred))

